version: '3'
services:

  db-mysql:
    image: mysql:5.7
    restart: always
    container_name: order-table-db
    environment:
      - MYSQL_DATABASE=order_table_db
      - MYSQL_ROOT_PASSWORD=zaq1@WSX
    ports:
      - "7033:3306"
    volumes:
      - /usr/app/order-table-db:/var/lib/mysql

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: order-table-proxy
    ports:
      - '4300:80'

  # client:
  #   build:
  #     context: ./frontend
  #   container_name: order-table-client
  #   volumes:
  #     - /app/node_modules

  backend:
    restart: always
    build:
      context: ./backend
    container_name: order-table-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql/order_table_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=zaq1@WSX
    depends_on:
      - db-mysql